name: Auto Deploy to Expo

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: expo-deploy
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Install Expo CLI
        run: npm install -g @expo/cli
        
      - name: Login to Expo
        run: npx expo login --non-interactive --token "${{ secrets.EXPO_TOKEN }}"
        
      - name: Deploy to Expo
        run: npx expo publish
